name: image_gallery_picker
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
   


  # Main packages for our app
  tflite: ^1.1.2
  image_picker: ^0.8.3+2
  image: ^4.0.10
  path_provider: ^2.0.11


  



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/model4.tflite
    - assets/labels1.txt